version: "3.8"
services:
  web-server:
    container_name: web-server
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "5001:80"
    volumes:
      - ./nginx/conf/default.conf /etc/nginx/conf.d/
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "5002:8000"
    working_dir: /app/
    tty: true
    volumes:
      - ./app:/app
