version: "3.8"
services:
  client:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:8000"
    working_dir: /app/
    tty: true
    volumes:
      - .:/app
